---
brew_taps:
  - cloudfoundry/tap
  - starkandwayne/cf
brew_casks:
  - clipy
  - dbeaver-community
  - deskpad
  - docker
  - firefox
  - iterm2
  - lastpass
  - microsoft-azure-storage-explorer
  - miniconda
  - postman
  - rectangle
  - scroll-reverser
  - spotify
  - sublime-text
  - visual-studio-code
  - vysor
brew_packages:
  - ansible
  - asdf
  - azure-cli
  - cf-cli
  - dotnet-sdk
  - git
  - gradle
  - jq
  - kotlin
  - maven
  - ripgrep
  - starkandwayne/cf/safe
  - stow
  - stunnel
  - tldr
  - tmux
  - vault
  - watchman
