---
- name: Including vars
  ansible.builtin.include_vars:
    file: vars/brew-packages.yml

- name: Adding taps
  community.general.hombrew_tap:
    name: "{{ homebrew_taps }}"
    state: present
  register: result
  until: result is successful

- name: Updating Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Upgrade Homebrew Packages
  community.general.homebrew:
    upgrade_all: true
  register: result
  until: result is successful

- name: Upgrade Homebrew Cask Packages
  community.general.homebrew_cask:
    upgrade_all: true
  register: result
  until: result is successful

- name: Install Homebrew Packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: present
  register: result
  until: result is successful

- name: Install Homebrew Cask Packages
  community.general.homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
  register: result
  until: result is successful
