---
- name: Homebrew | Including vars
  ansible.builtin.include_vars:
    file: vars/brew-packages.yml
  tags:
    - brew

- name: Homebrew | Adding taps
  community.general.homebrew_tap:
    name: "{{ brew_taps }}"
    state: present
  register: result
  until: result is successful
  tags:
    - brew

- name: Homebrew | Update Homebrew and upgrade all packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  register: result
  until: result is successful
  tags:
    - brew-update

- name: Homebrew | Install Homebrew Packages
  community.general.homebrew:
    name: "{{ package_item }}" 
    state: present
  retries: 5
  delay: 3
  register: install_package
  until: install_package is not failed
  when: brew_packages | length > 0
  loop: "{{ brew_packages }}"
  loop_control:
    loop_var: package_item
  tags:
    - brew

- name: Homebrew | Install Homebrew Cask Packages
  community.general.homebrew_cask:
    name: "{{ cask_item }}" 
    state: present
    greedy: True
  retries: 5
  delay: 3
  register: install_cask
  until: install_cask is not failed
  when: brew_casks | length > 0
  loop: "{{ brew_casks }}"
  loop_control:
    loop_var: cask_item
  tags:
    - brew
