---
- name: Check if Oh-My-Zsh is installed
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_path
  
- name: Installing Oh-My-Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
  when: not oh_my_zsh_path.stat.exists

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  tags:
    - update

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  tags:
    - update
